version: "1.0"
services:
  postgres-survey:
    image: postgres:13.1
    environment:
      POSTGRES_DB: "survey"
      POSTGRES_USER: "project_basic"
      POSTGRES_PASSWORD: "survey"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /Users/justoleg/Documents/postgresql/data:/var/lib/postgresql/data/pgdata
    ports:
      - "5431:5432"